version: '3.8'
volumes:
  zksingle-ksingle_kafka1-data:
  zksingle-ksingle_zoo1-data:
  zksingle-ksingle_zoo1-log:

services:
  sftp-server:
    image: atmoz/sftp
    hostname: sftp-server
    container_name: sftp-server
    volumes:
      - ~/sftp-files/upload:/home/tester/upload
    ports:
      - "22:22"
    command: tester:password:1001:::upload

  zoo1:
    image: confluentinc/cp-zookeeper:6.2.1
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888
    volumes:
      - type: volume
        source: zksingle-ksingle_zoo1-data
        target: /data
      - type: volume
        source: zksingle-ksingle_zoo1-log
        target: /datalog

  kafka1:
    image: confluentinc/cp-kafka:6.2.1
    hostname: kafka1
    container_name: kafka1
    user: "appuser:appuser"
    ports:
      - "9092:9092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
    volumes:
      - type: volume
        source: zksingle-ksingle_kafka1-data
        target: /var/lib/kafka/data
    depends_on:
      - zoo1

  kafka-bootstrap-topics:
    image: confluentinc/cp-kafka:6.2.1
    depends_on:
      - kafka1
    hostname: kafka-bootstrap-topics
    container_name: kafka-bootstrap-topics
    command: ["bash", "./bootstrap-topics.sh"]
    working_dir: /scripts/kafka
    volumes:
      - ./scripts:/scripts

  kafka-schema-registry:
    image: confluentinc/cp-schema-registry:6.2.1
    hostname: kafka-schema-registry
    container_name: kafka-schema-registry
    depends_on:
      - zoo1
      - kafka1
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://kafka1:19092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  kafka-control-center:
    image: confluentinc/cp-enterprise-control-center:6.2.1
    hostname: kafka-control-center
    container_name: kafka-control-center
    depends_on:
      - zoo1
      - kafka1
      - kafka-schema-registry
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka1:19092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zoo1:2181'
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://kafka-schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021


  aws-localstack:
    image: localstack/localstack:latest
    hostname: aws-localstack
    container_name: aws-localstack
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DEFAULT_REGION=south-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - '4566:4566'
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "./scripts/aws:/docker-entrypoint-initaws.d"


  connect-config-server:
    image: cristianpbht/bh-connect-config-server:v.0.0.1
    hostname: connect-config-server
    container_name: connect-config-server
    ports:
      - '8888:8888'
    environment:
      - GITHUB_URL=https://github.com/cristian-agreda/bh-configuration-files

  connect-sftp-statements:
    image: cristianpbht/sftp-statements:v.0.0.3
    ##  image: sftp-statements:v.0.0.3
    hostname: connect-sftp-statements
    container_name: connect-sftp-statements
    ports:
      - '8080:8080'
    environment:
      - CONFIG_SERVER_URL=http://connect-config-server:8888
      - CONFIG_SERVER_PROFILE=dev
    depends_on:
      - connect-config-server
      - sftp-server
      - zoo1
      - kafka1
      - kafka-schema-registry
      - aws-localstack
