#Kafka
spring:
  kafka:
    bootstrap-servers: http://kafka1:9092
    consumer:
      group-id: FIRST_GROUP

#Schema Registry Url
schema:
  registry:
    url: http://kafka-schema-registry:8081

#AWS S3 configuration settings
s3:
  config:
    url: http://aws-localstack:4566
    region: south-east-1
    access-key-id: test
    secret-key-id: test

server:
  port: 8086

logging:
  file:
    name: transformation.log
    path: ./log/
